/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package SistemaVentas;
import java.awt.event.ItemEvent;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.DefaultComboBoxModel;
/**
 *
 * @author fam
 */
public class productos extends javax.swing.JFrame {
    DefaultTableModel model=new DefaultTableModel();
    /**
     * Creates new form productos
     */
    public productos() {
        initComponents();
        
        model.addColumn("Producto");
        this.textotabla.setModel(model);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tipoproducto = new javax.swing.JComboBox();
        jScrollPane2 = new javax.swing.JScrollPane();
        textotabla = new javax.swing.JTable();
        agregar = new javax.swing.JButton();
        eliminar = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        comprar = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        listaproducto = new javax.swing.JComboBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tipoproducto.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Seleccione el tipo de producto:", "Lacteos", "Carnes", "Higiene", "Aseo del hogar", "Vegetales", "Salsas", "Panes", "Frutas", " ", " " }));
        tipoproducto.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                tipoproductoItemStateChanged(evt);
            }
        });

        textotabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "Title 1"
            }
        ));
        jScrollPane2.setViewportView(textotabla);

        agregar.setText("Agregar");
        agregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregarActionPerformed(evt);
            }
        });

        eliminar.setText("Eliminar");
        eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminarActionPerformed(evt);
            }
        });

        jButton3.setText("volver al menú");
        jButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton3MouseClicked(evt);
            }
        });

        comprar.setText("Comprar");
        comprar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                comprarMouseClicked(evt);
            }
        });
        comprar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comprarActionPerformed(evt);
            }
        });

        jButton1.setText("Eliminar todo");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tipoproducto, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 306, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton3, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(comprar)
                            .addComponent(agregar))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(eliminar)
                            .addComponent(jButton1)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(listaproducto, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(24, 24, 24))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tipoproducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(listaproducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(240, 240, 240)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(agregar)
                            .addComponent(eliminar))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(comprar)
                            .addComponent(jButton1))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                .addComponent(jButton3)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    public String[] getProductos(String tipoproducto){
        String[] Productos = new String[5];
        if(tipoproducto.equalsIgnoreCase("Lacteos")){
            Productos[0]= "Leche";
            Productos[1]= "Queso";
            Productos[2]= "Mantequilla";
            Productos[3]= "Margarina";
            Productos[4]= "Yogur";
        }
        if(tipoproducto.equalsIgnoreCase("Carnes")){
            Productos[0]= "Pollo";
            Productos[1]= "Carne de ternera";
            Productos[2]= "Pescado";
            Productos[3]= "carne de cerdo";
            Productos[4]= "jamón";
        }
        if(tipoproducto.equalsIgnoreCase("Aseo del hogar")){
            Productos[0]= "Escoba";
            Productos[1]= "Recogedor";
            Productos[2]= "Ace";
            Productos[3]= "Azistin";
            Productos[4]= "Trapeador";
        }
        if(tipoproducto.equalsIgnoreCase("Higiene")){
            Productos[0]= "Papel higienico";
            Productos[1]= "cepillo de dientes";
            Productos[2]= "jabon liquido";
            Productos[3]= "afeitadora";
            Productos[4]= "shampoo";
        }
        if(tipoproducto.equalsIgnoreCase("Vegetales")){
            Productos[0]= "Lechuga";
            Productos[1]= "Tomate";
            Productos[2]= "Remolacha";
            Productos[3]= "Cebolla";
            Productos[4]= "Zanahoria";
        }
        if(tipoproducto.equalsIgnoreCase("Salsas")){
            Productos[0]= "Ketchup";
            Productos[1]= "Mostaza";
            Productos[2]= "Mayonesa";
            Productos[3]= "Salsa inglesa";
            Productos[4]= "Salsa soya";
        }
        if(tipoproducto.equalsIgnoreCase("Panes")){
            Productos[0]= "Pan molde";
            Productos[1]= "Pan baguette";
            Productos[2]= "Semitas";
            Productos[3]= "Pan integral";
            Productos[4]= "Marquesote";
        }
        if(tipoproducto.equalsIgnoreCase("Frutas")){
            Productos[0]= "Banano";
            Productos[1]= "Manzana";
            Productos[2]= "Sandia";
            Productos[3]= "Pera";
            Productos[4]= "Fresas";
        }
        
        return Productos;
    }
    private void agregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregarActionPerformed
        String []agregar = new String[1];
        if(listaproducto.getSelectedIndex()==-1){
           agregar[0]= "seleccione un producto"; 
        }else{
            agregar[0] = listaproducto.getSelectedItem().toString();
        }    
        model.addRow(agregar);
        
    }//GEN-LAST:event_agregarActionPerformed

    private void eliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminarActionPerformed
        int elimina=textotabla.getSelectedRow();
        if(elimina>=0){
            model.removeRow(elimina);
        }else{
            JOptionPane.showMessageDialog(null, "No ha seleccionado un producto");
        }
        
    }//GEN-LAST:event_eliminarActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        int eliminartodo=textotabla.getRowCount();
        for(int i=eliminartodo-1; i>=0;i--){
            model.removeRow(i);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void tipoproductoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_tipoproductoItemStateChanged
        if(evt.getStateChange()== ItemEvent.SELECTED){
           if(this.tipoproducto.getSelectedIndex()>0){
               this.listaproducto.setModel(new DefaultComboBoxModel(this.getProductos(this.tipoproducto.getSelectedItem().toString())));
           }
        }       
    }//GEN-LAST:event_tipoproductoItemStateChanged

    private void jButton3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MouseClicked
        Ventas ventas= new Ventas();
        ventas.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton3MouseClicked

    private void comprarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comprarActionPerformed
        
    }//GEN-LAST:event_comprarActionPerformed

    private void comprarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_comprarMouseClicked
        Confirmar confirmar= new Confirmar();
        confirmar.setVisible(true);
    }//GEN-LAST:event_comprarMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(productos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(productos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(productos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(productos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new productos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton agregar;
    private javax.swing.JButton comprar;
    private javax.swing.JButton eliminar;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JComboBox listaproducto;
    private javax.swing.JTable textotabla;
    private javax.swing.JComboBox tipoproducto;
    // End of variables declaration//GEN-END:variables
}
